// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieBooking.Data;

#nullable disable

namespace MovieBooking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260228140311_AddAdminFields")]
    partial class AddAdminFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieBooking.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShowtimeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("ShowtimeId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            CreatedAt = new DateTime(2026, 2, 27, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ShowtimeId = 1,
                            TotalPrice = 486000m,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("MovieBooking.Models.BookingDetail", b =>
                {
                    b.Property<int>("BookingDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDetailId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("BookingDetailId");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("MovieBooking.Models.Cinema", b =>
                {
                    b.Property<int>("CinemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CinemaId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CinemaId");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            CinemaId = 1,
                            Address = "Quận 1",
                            Name = "CGV Vincom"
                        },
                        new
                        {
                            CinemaId = 2,
                            Address = "Quận 7",
                            Name = "Lotte Cinema"
                        },
                        new
                        {
                            CinemaId = 3,
                            Address = "Quận 1",
                            Name = "Galaxy Nguyen Du"
                        },
                        new
                        {
                            CinemaId = 4,
                            Address = "Quận 10",
                            Name = "BHD Star"
                        });
                });

            modelBuilder.Entity("MovieBooking.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("AgeRestriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Producer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            AgeRestriction = "T13",
                            Cast = "Leonardo DiCaprio",
                            Description = "Phim khoa học viễn tưởng về giấc mơ.",
                            Director = "Christopher Nolan",
                            DurationMinutes = 148,
                            Genre = "Sci-Fi, Action",
                            IsActive = true,
                            PosterUrl = "/images/inception.jpg",
                            Producer = "Emma Thomas",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 2,
                            AgeRestriction = "P",
                            Cast = "Jack Black, Dustin Hoffman",
                            Description = "Chú gấu trúc Po trở thành chiến binh rồng bảo vệ thung lũng.",
                            Director = "Mark Osborne, John Stevenson",
                            DurationMinutes = 92,
                            Genre = "Animation, Comedy",
                            IsActive = true,
                            PosterUrl = "/images/kungfu.jpg",
                            Producer = "Melissa Cobb",
                            ReleaseDate = new DateTime(2008, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Kung Fu Panda"
                        },
                        new
                        {
                            MovieId = 3,
                            AgeRestriction = "T13",
                            Cast = "Robert Downey Jr., Gwyneth Paltrow",
                            Description = "Tony Stark chế tạo bộ giáp công nghệ cao và trở thành Iron Man.",
                            Director = "Jon Favreau",
                            DurationMinutes = 126,
                            Genre = "Action, Superhero",
                            IsActive = true,
                            PosterUrl = "/images/ironman.jpg",
                            Producer = "Kevin Feige",
                            ReleaseDate = new DateTime(2008, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Man"
                        },
                        new
                        {
                            MovieId = 4,
                            AgeRestriction = "T13",
                            Cast = "Johnny Depp, Orlando Bloom",
                            Description = "Thuyền trưởng Jack Sparrow phiêu lưu trên biển Caribbean.",
                            Director = "Gore Verbinski",
                            DurationMinutes = 143,
                            Genre = "Adventure, Fantasy",
                            IsActive = true,
                            PosterUrl = "/images/pirates.jpg",
                            Producer = "Jerry Bruckheimer",
                            ReleaseDate = new DateTime(2003, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pirates of the Caribbean"
                        });
                });

            modelBuilder.Entity("MovieBooking.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Row")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeatId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("MovieBooking.Models.Showtime", b =>
                {
                    b.Property<int>("ShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShowtimeId"));

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowtimeId");

                    b.HasIndex("CinemaId");

                    b.HasIndex("MovieId");

                    b.ToTable("Showtimes");

                    b.HasData(
                        new
                        {
                            ShowtimeId = 1,
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 2, 27, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 27, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 2,
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 2, 27, 23, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 27, 21, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 3,
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 2, 27, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 120000m,
                            StartTime = new DateTime(2026, 2, 27, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 4,
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 2, 27, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 27, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 5,
                            CinemaId = 3,
                            EndTime = new DateTime(2026, 2, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 28, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 6,
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 2, 27, 18, 40, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Price = 120000m,
                            StartTime = new DateTime(2026, 2, 27, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 7,
                            CinemaId = 4,
                            EndTime = new DateTime(2026, 2, 28, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 28, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 8,
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 2, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 28, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 9,
                            CinemaId = 3,
                            EndTime = new DateTime(2026, 2, 28, 23, 15, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 3,
                            Price = 180000m,
                            StartTime = new DateTime(2026, 2, 28, 21, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 10,
                            CinemaId = 4,
                            EndTime = new DateTime(2026, 3, 1, 20, 50, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 3, 1, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 11,
                            CinemaId = 1,
                            EndTime = new DateTime(2026, 3, 1, 23, 20, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 4,
                            Price = 180000m,
                            StartTime = new DateTime(2026, 3, 1, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 12,
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 2, 28, 17, 40, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 2,
                            Price = 120000m,
                            StartTime = new DateTime(2026, 2, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 13,
                            CinemaId = 3,
                            EndTime = new DateTime(2026, 2, 28, 22, 30, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 28, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 14,
                            CinemaId = 4,
                            EndTime = new DateTime(2026, 2, 28, 21, 15, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 150000m,
                            StartTime = new DateTime(2026, 2, 28, 19, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 15,
                            CinemaId = 4,
                            EndTime = new DateTime(2026, 2, 27, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 180000m,
                            StartTime = new DateTime(2026, 2, 27, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowtimeId = 16,
                            CinemaId = 2,
                            EndTime = new DateTime(2026, 2, 27, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            MovieId = 1,
                            Price = 120000m,
                            StartTime = new DateTime(2026, 2, 27, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MovieBooking.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@example.com",
                            Name = "Test User",
                            PasswordHash = "dummy_hash",
                            Role = "User",
                            Username = "testuser"
                        });
                });

            modelBuilder.Entity("MovieBooking.Models.Booking", b =>
                {
                    b.HasOne("MovieBooking.Models.Showtime", "Showtime")
                        .WithMany("Bookings")
                        .HasForeignKey("ShowtimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieBooking.Models.BookingDetail", b =>
                {
                    b.HasOne("MovieBooking.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.Models.Seat", "Seat")
                        .WithMany("BookingDetails")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("MovieBooking.Models.Seat", b =>
                {
                    b.HasOne("MovieBooking.Models.Cinema", "Cinema")
                        .WithMany("Seats")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("MovieBooking.Models.Showtime", b =>
                {
                    b.HasOne("MovieBooking.Models.Cinema", "Cinema")
                        .WithMany("Showtimes")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieBooking.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieBooking.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("MovieBooking.Models.Cinema", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MovieBooking.Models.Movie", b =>
                {
                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("MovieBooking.Models.Seat", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("MovieBooking.Models.Showtime", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MovieBooking.Models.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
